#!/bin/sh

### BEGIN INIT INFO
# Provides:          heating-controll
# Required-Start:    $network $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Central Heating controller script
# Description:       This scripts start and stops the Awesome CH Controller
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:
INSTALL_DIR=/usr/local/

DESC="Heating Controller"
VERSION="2.0.0-SNAPSHOT"
JNI_LOCATION="/usr/lib/jni"
JAR_FILE="temperature-sensor-and-rest-${VERSION}-fat.jar"
PID_FILE=/var/run/heating-controller.pid

. /lib/lsb/init-functions

start () {
    echo -n "Starting $DESC: "
    if [ -f $PID_FILE ]; then
         OLD_PID=`cat $PID_FILE`
         kill -9 $OLD_PID
         rm -rf $PID_FILE
    fi
    java -jar $JAR_FILE  -conf prod.json > /dev/null 2>&1 &

    PID=$!

    if [ $? != 0 ]; then
        log_failure_message "Process started with errors"
        exit 1
    fi

    echo $PID > $PID_FILE

    log_success_message "Service started with PID $PID"
}


stop () {
    if [ -f $PID_FILE ]; then
        OLD_PID=`cat $PID_FILE`
        kill -9 $OLD_PID
        rm -rf $PID_FILE
        log_success_message "Heating Controller stopped"
    else
        log_success_message "Nothing seems to be running anyway"
    fi
    exit 0
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        echo -n "Restarting $DESC: "
        stop
        sleep 1
        start
        ;;
    status)
        status_of_proc -p $PID_FILE && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $NAME {start|stop|restart|status}" >&2
        exit 1
        ;;
    esac

exit 0