
export const TOGGLE_SCHEDULE = 'TOGGLE_SCHEDULE';

export const DAY_SCHEDULE_UPDATE_TIME = 'DAY_SCHEDULE_UPDATE_TIME';
export const DAY_SCHEDULE_UPDATE_TEMP = 'DAY_SCHEDULE_UPDATE_TEMP';

export const DAY_SCHEDULE_ADD_HOUR = 'DAY_SCHEDULE_ADD_HOUR';
export const DAY_SCHEDULE_REMOVE_HOUR = 'DAY_SCHEDULE_REMOVE_HOUR';
export const DAY_SCHEDULE_COPY = 'DAY_SCHEDULE_COPY';


export const SCHEDULE_REQUEST = 'SCHEDULE_REQUEST';
export const SCHEDULE_RECEIVE = 'SCHEDULE_RECEIVE';